Add command snippet
Azure/azureml-web pull request #36
Opened 2021-02-18 00:08 UTC by aminsaied

# PR into Azure/azureml-web

## Checklist

I have:

- [x] read and followed the contributing guidelines

## Changes

- Add a new snippet that uses command argument
- Update the snippets.md page to reflect this change
- Noticed that the automatic tool for updating snippets.md had a stale link, so updated that link too

This will close the associated issue.

2021-02-18 19:30 UTC, mx-iao approved these changes

2021-02-19 19:28 UTC, AbeOmor requested changes
LGTM! except the comment I made around the doc links

2021-02-19 19:28 UTC, AbeOmor commented on website/docs/vs-code-snippets/python.json
>          "description": "Set up ScriptRunConfig including compute target, environment and experiment"
Should we start adding Docs to the snippet Descriptions? For this one I didn't really understand command until I read the docs. https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.script_run_config.scriptrunconfig?view=azure-ml-py#constructor

2021-02-19 21:54 UTC, AbeOmor commented on website/docs/vs-code-snippets/python.json
>          "description": "Set up ScriptRunConfig including compute target, environment and experiment"
Actually no worries. Adding docs is not necessary. If we need to add docs link, we need to add to all snippets

2021-02-19 21:54 UTC, AbeOmor approved these changes

2021-02-22 16:15 UTC, merged